version: '3.8'

services:
  schedule-app:
    image: schedule-app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - postgres-db
    container_name: schedule-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  postgres-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university_db
    container_name: postgres-db