spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/university_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none